"""Add AuditLog schema

Revision ID: 2f8f10034ccf
Revises: f2fe2c5cdace
Create Date: 2026-06-06 16:33:00.868837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                 # SELF_ADDED


# revision identifiers, used by Alembic.
revision: str = '2f8f10034ccf'
down_revision: Union[str, Sequence[str], None] = 'f2fe2c5cdace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditlog')
    # ### end Alembic commands ###
